### ISSUE TITLE
withdrawal of fees error

### ISSUE THREAD

**Issue by scottmatheina** [republicprotocol/republic-sol#29]
**Description**

Attempted to withdrawal REN and ABC from darknode. Metamask wallet displays 

ALERT: Transaction Error. Exception thrown in contract code 
and contract gives
![ren error](https://user-images.githubusercontent.com/10782022/43986481-f8db9452-9cd6-11e8-9e5d-803ad2109db1.png)

Contract 0x5d62ccc1086f38286dc152962a4f3e337eec1ec1  
 Warning! Error encountered during contract execution [Reverted] 

https://kovan.etherscan.io/tx/0xfa08296a1fcd764da633b6b8215670126935851d3ecaf60e1581f22f9cf40b88 > example tx id from failed transaction. 

Metamask address is 0x423f7a5f5b33a39b6db98f4b57126d35eb7e1b04
darknode eth address is 0x915d3214d40bc8661552Cf0Cc6628816c2727B2C
darknode ip address is 54.201.93.60

**Expected Behavior**

Click "withdrawal" on darknode and receive funds in metamask wallet

**Steps to reproduce**

click 'withdrawal"
metamask is unlocked, and asks to confirm transaction. 
metamask displays "ALERT: Transaction Error. Exception thrown in contract code "
and once confirmed, tx will pend and then give error. 

**Version**

MetaMask Version
4.9.2

**Operating system**

Google Chrome Version 68.0.3440.84 (Official Build) (64-bit)
Ubuntu Linux 18.04.1

**Comment by negaex** [comment]
Thanks for reporting the issue - the contract holding the fees was talking to a previous version of the darknode registration contract.

This has been updated now - if you try to withdraw the fees it should work again.
