### ISSUE TITLE
Update test suite

### ISSUE THREAD

**Issue by loongy** [republicprotocol/republic-sol#8]
Substantial changes to the Solidity contracts have rendered our testing suite obsolete. We need to address this immediately. Each Solidity contract should have a dedicated test file configured for use with Truffle, that can be executed and verified by our CI.

**Comment by susruth** [comment]
The tests written in typescript are complicated, would we want to make it simpler by just using javascript instead?

**Comment by loongy** [comment]
Having Typescript in there certainly adds noise to the process of building/running tests. I would be find if the Typescript tests were removed in favor of vanilla JavaScript. In general, I think tests are simple enough that Typescript isn't necessary.

**Comment by susruth** [comment]
Created a pull request addressing this issue #9

**Comment by susruth** [comment]
Created a pull request addressing this issue #9
